### ISSUE TITLE
error: cannot assign to readonly variable: PRODUCT_PACKAGES

### ISSUE THREAD

**Issue by NavlysChen** [TheXPerienceProject/android_hardware_qcom_display#1]
When i wanted to build xperience for xiaomi_sirius, it had this error. And i couldn't find any similar errors for github.

```
lunch xperience_sirius-userdebug
In file included from build/make/core/config.mk:302:
In file included from vendor/xperience/config/BoardConfigXPerience.mk:7:
In file included from vendor/xperience/config/BoardConfigQcom.mk:129:
hardware/qcom/display/sdm845/config/display-product.mk:2: error: cannot assign to readonly variable: PRODUCT_PACKAGES
11:01:25 dumpvars failed with: exit status 1
Device sirius not found. Attempting to retrieve device repository from The XPerience Project Github (http://github.com/TheXPerienceProject).
Repository for sirius not found in The XPerience Project Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
In file included from build/make/core/config.mk:302:
In file included from vendor/xperience/config/BoardConfigXPerience.mk:7:
In file included from vendor/xperience/config/BoardConfigQcom.mk:129:
hardware/qcom/display/sdm845/config/display-product.mk:2: error: cannot assign to readonly variable: PRODUCT_PACKAGES
11:01:27 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:302:
In file included from vendor/xperience/config/BoardConfigXPerience.mk:7:
In file included from vendor/xperience/config/BoardConfigQcom.mk:129:
hardware/qcom/display/sdm845/config/display-product.mk:2: error: cannot assign to readonly variable: PRODUCT_PACKAGES
11:01:28 dumpvars failed with: exit status 1

** Don't have a product spec for: 'xperience_sirius'
** Do you have the right repo manifest?
```

The device tree I used is as follows
https://github.com/crdroidandroid/android_device_xiaomi_sdm710-common/tree/11.0
https://github.com/crdroidandroid/android_device_xiaomi_sirius/tree/11.0
https://github.com/DevelopedInside/proprietary_vendor_xiaomi/tree/lineage-18.0
https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710

**Comment by Klozz** [comment]
repo sync to vendor/xperience and you can build.

**Comment by NavlysChen** [comment]
> 回购同步到供应商/体验，就可以构建。
Thanks.But now it has new error for missing init.xperience.usb.rc. And it seems that the error was caused by the latest change in device/xperience/common/.
```
ninja: no work to do.
[100% 1/1] /home/navlys/XPe/out/soong/.bootstrap/bin/soong_build /home/navlys/XPe/out/soong/build.ninja
FAILED: /home/navlys/XPe/out/soong/build.ninja
/home/navlys/XPe/out/soong/.bootstrap/bin/soong_build -t -l /home/navlys/XPe/out/.module_paths/Android.bp.list -b /home/navlys/XPe/out/soong -n /home/navlys/XPe/out -d /home/navlys/XPe/out/soong/build.ninja.d -globFile /home/navlys/XPe/out/soong/.bootstrap/build-globs.ninja -o /home/navlys/XPe/out/soong/build.ninja Android.bp
Clang SA is not enabled
error: device/xperience/common/usb/Android.bp:15:1: module "init.xperience.usb.rc" variant "android_arm64_armv8-2a": module source path "device/xperience/common/usb/init.xperience.usb.rc" does not exist
ninja: build stopped: subcommand failed.
13:42:06 soong bootstrap failed with: exit status 1
```

**Comment by Klozz** [comment]
> > 回购同步到供应商/体验，就可以构建。
> > Thanks.But now it has new error for missing init.xperience.usb.rc. And it seems that the error was caused by the latest change in device/xperience/common/.
> 
> ```
> ninja: no work to do.
> [100% 1/1] /home/navlys/XPe/out/soong/.bootstrap/bin/soong_build /home/navlys/XPe/out/soong/build.ninja
> FAILED: /home/navlys/XPe/out/soong/build.ninja
> /home/navlys/XPe/out/soong/.bootstrap/bin/soong_build -t -l /home/navlys/XPe/out/.module_paths/Android.bp.list -b /home/navlys/XPe/out/soong -n /home/navlys/XPe/out -d /home/navlys/XPe/out/soong/build.ninja.d -globFile /home/navlys/XPe/out/soong/.bootstrap/build-globs.ninja -o /home/navlys/XPe/out/soong/build.ninja Android.bp
> Clang SA is not enabled
> error: device/xperience/common/usb/Android.bp:15:1: module "init.xperience.usb.rc" variant "android_arm64_armv8-2a": module source path "device/xperience/common/usb/init.xperience.usb.rc" does not exist
> ninja: build stopped: subcommand failed.
> 13:42:06 soong bootstrap failed with: exit status 1
> ```

sorry it seems that when I did the commit I forgot to add the file, I have already added it
please let me know if you have any other problem

repo sync device/xperience/common

**Comment by NavlysChen** [comment]
Threre is a obsolete matter from caf. How can i avoid it?
```
FAILED: 
external/wpa_supplicant_8/wpa_supplicant/Android.mk:30: warning: "Disabling OCV support in hostapd for sdm710"
external/wpa_supplicant_8/wpa_supplicant/Android.mk:37: warning: "Disabling SuiteB-192 support in wpa_supplicant for sdm710"
external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: libwpa_client: LOCAL_COPY_HEADERS is obsolete. See https://android.googlesource.com/platform/build/+/master/Changes.md#copy_headers 
In file included from build/make/core/prebuilt.mk:60:
In file included from external/wpa_supplicant_8/Android.mk:9:
In file included from external/wpa_supplicant_8/wpa_supplicant/Android.mk:1841:
build/make/core/shared_library.mk:80: error: done.
```

**Comment by Klozz** [comment]
> Threre is a obsolete matter from caf. How can i avoid it?
> 
> ```
> FAILED: 
> external/wpa_supplicant_8/wpa_supplicant/Android.mk:30: warning: "Disabling OCV support in hostapd for sdm710"
> external/wpa_supplicant_8/wpa_supplicant/Android.mk:37: warning: "Disabling SuiteB-192 support in wpa_supplicant for sdm710"
> external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: libwpa_client: LOCAL_COPY_HEADERS is obsolete. See https://android.googlesource.com/platform/build/+/master/Changes.md#copy_headers 
> In file included from build/make/core/prebuilt.mk:60:
> In file included from external/wpa_supplicant_8/Android.mk:9:
> In file included from external/wpa_supplicant_8/wpa_supplicant/Android.mk:1841:
> build/make/core/shared_library.mk:80: error: done.
> ```

try this.
https://github.com/TheXPerienceProject/android_device_xiaomi_lavender/commit/5cbc4cea3ab73914e899a1a628d853aba6d5b90a

**Comment by NavlysChen** [comment]
> > Threre is a obsolete matter from caf. How can i avoid it?
> > ```
> > FAILED: 
> > external/wpa_supplicant_8/wpa_supplicant/Android.mk:30: warning: "Disabling OCV support in hostapd for sdm710"
> > external/wpa_supplicant_8/wpa_supplicant/Android.mk:37: warning: "Disabling SuiteB-192 support in wpa_supplicant for sdm710"
> > external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: libwpa_client: LOCAL_COPY_HEADERS is obsolete. See https://android.googlesource.com/platform/build/+/master/Changes.md#copy_headers 
> > In file included from build/make/core/prebuilt.mk:60:
> > In file included from external/wpa_supplicant_8/Android.mk:9:
> > In file included from external/wpa_supplicant_8/wpa_supplicant/Android.mk:1841:
> > build/make/core/shared_library.mk:80: error: done.
> > ```
> 
> try this.
> [TheXPerienceProject/android_device_xiaomi_lavender@5cbc4ce](https://github.com/TheXPerienceProject/android_device_xiaomi_lavender/commit/5cbc4cea3ab73914e899a1a628d853aba6d5b90a)

Thx bro, the LOCAL_COPY_HEADERS was solved. But now it has a new problem, i can't find any solution from github or google.
```
[ 99% 416/418] including /home/navlys/XPe/out/soong/late-xperience_sirius.mk ...
[ 99% 417/418] finishing build rules ...
FAILED: 
vendor/qcom/opensource/wlan/utils/sigma-dut/Android.mk: error: "sigma_dut (native:platform) can not link against libpcap.vendor (native:vendor)" 
vendor/qcom/opensource/wlan/utils/sigma-dut/Android.mk: error: "sigma_dut (native:platform) can not link against libwifi-hal-qcom (native:vendor)" 
build/make/core/main.mk:961: error: exiting from previous errors.
11:05:16 ckati failed with: exit status 1
```
if i copy libwifi-hal-qcom.so from miui's vendor, and add description in vendor/xiaomi/sdm710-common/Android.bp.
```
cc_prebuilt_library_shared {
	name: "libwifi-hal-qcom.so",
	owner: "xiaomi",
	strip: {
		none: true,
	},
	target: {
		android_arm: {
			srcs: ["proprietary/vendor/lib/libwifi-hal-qcom.so"],
		},
		android_arm64: {
			srcs: ["proprietary/vendor/lib64/libwifi-hal-qcom.so"],
		},
	},
	compile_multilib: "both",
	prefer: true,
	soc_specific: true,
}
```
And then it shows
```
[ 88% 993/1124] including hardware/qcom/media/sm8150/Android.mk ...
[ 88% 994/1124] including hardware/qcom/wlan/Android.mk ...
FAILED: 
In file included from hardware/qcom/media/sm8150/Android.mk:1:
In file included from hardware/qcom/wlan/Android.mk:3:
In file included from hardware/qcom/wlan/qcwcn/Android.mk:4:
In file included from hardware/qcom/wlan/qcwcn/wifi_hal/Android.mk:181:
In file included from build/make/core/shared_library.mk:37:
In file included from build/make/core/shared_library_internal.mk:34:
In file included from build/make/core/dynamic_binary.mk:39:
In file included from build/make/core/binary.mk:9:
build/make/core/base_rules.mk:339: error: hardware/qcom/wlan/qcwcn/wifi_hal: MODULE.TARGET.SHARED_LIBRARIES.libwifi-hal-qcom already defined by vendor/xiaomi/sdm710-common.
10:52:43 ckati failed with: exit status 1
```
I don’t know if this is a vendor issue or a code issue, so I’m here to ask.

**Comment by Klozz** [comment]
> vendor/qcom/opensource/wlan/utils/sigma-dut

you can get rid of it
rm -rf vendor/qcom/opensource/wlan/utils/sigma-dut
I will remove it from the manifest

**Comment by NavlysChen** [comment]
Sorry i'm here again for help.
```
[ 51% 82170/159540] //hardware/qcom/display/sdm845/libqdutils:libqdutils clang++ display_config.cpp
FAILED: /home/navlys/XPe/out/soong/.intermediates/hardware/qcom/display/sdm845/libqdutils/libqdutils/android_vendor.30_arm64_armv8-2a_shared/obj/hardware/qcom/display/sdm845/libqdutils/display_config.o
PWD=/proc/self/cwd /usr/bin/ccache vendor/qcom/sdclang/bin/clang++ -c -Wno-enum-compare -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -Wno-null-dereference -Wno-pointer-compare -Wno-xor-used-as-pow -Wno-final-dtor-non-final-class -D__ANDROID_VNDK__  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wno-c99-designator -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -march=armv8.2a  -target aarch64-linux-android30 -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -fPIC -Wsign-promo -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -Ihardware/qcom/display/sdm845/libqdutils -Ihardware/qcom/display/sdm845/include -Ihardware/qcom/display/sdm845/libcopybit -Ihardware/qcom/display/sdm845/libdrmutils -Ihardware/qcom/display/sdm845/libqdutils -Ihardware/qcom/display/sdm845/libqservice -Ihardware/qcom/display/sdm845/gpu_tonemapper -Ihardware/qcom/display/sdm845/sdm/include -Ihardware/qcom/display/sdm845/gralloc -Ihardware/qcom/display/sdm845/libdebug -Ihardware/libhardware/include -Isystem/media/audio/include -Isystem/core/libcutils/include_vndk -Isystem/core/libsystem/include -Isystem/bt/types -Ivendor/qcom/opensource/commonsys-intf/display/gralloc -Ivendor/qcom/opensource/commonsys-intf/display/include -Ivendor/qcom/opensource/commonsys-intf/display/libqdmetadata -Ivendor/qcom/opensource/commonsys-intf/display/services -Isystem/core/libutils/include -Isystem/core/libbacktrace/include -Isystem/core/liblog/include_vndk -Isystem/core/libprocessgroup/include -Iexternal/libcxxabi/include -Isystem/core/libcutils/include -Iframeworks/native/libs/binder/include -Isystem/core/base/include -I/home/navlys/XPe/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-2a_shared/gen/aidl -Iexternal/libcxx/include -isystem /home/navlys/XPe/out/soong/.intermediates/bionic/libc/libc.llndk/android_vendor.30_arm64_armv8-2a_shared/gen/include -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -Wno-missing-field-initializers -Wconversion -Wall -Werror '-DLOG_TAG="qdutils"' -Wno-sign-conversion -DDO_NOT_CHECK_MANUAL_BINDER_INTERFACES -std=gnu++17 -fno-rtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-string-compare -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-pessimizing-move  -Wno-alloca -Wno-bool-operation -Wno-c++17-extensions -Wno-c99-designator -Wno-dangling-gsl -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-copy -Wno-deprecated-enum-enum-conversion -Wno-final-dtor-non-final-class -Wno-implicit-fallthrough -Wno-implicit-int-float-conversion -Wno-incomplete-setjmp-declaration -Wno-int-in-bool-context -Wno-invalid-partial-specialization -Wno-misleading-indentation -Wno-pointer-compare -Wno-range-loop-analysis -Wno-reorder-init-list -Wno-sizeof-array-div-Wno-xor-used-as-pow -Wno-string-compare -Wno-tautological-overlap-compare -Wno-thread-safety-analysis -Wno-unknown-warning-option -Wno-unsequenced -Wno-unused-comparison -Wno-wrong-info -Wno-zero-as-null-pointer-constant -flax-vector-conversions=all -fsplit-lto-unit -MD -MF /home/navlys/XPe/out/soong/.intermediates/hardware/qcom/display/sdm845/libqdutils/libqdutils/android_vendor.30_arm64_armv8-2a_shared/obj/hardware/qcom/display/sdm845/libqdutils/display_config.o.d -o /home/navlys/XPe/out/soong/.intermediates/hardware/qcom/display/sdm845/libqdutils/libqdutils/android_vendor.30_arm64_armv8-2a_shared/obj/hardware/qcom/display/sdm845/libqdutils/display_config.o hardware/qcom/display/sdm845/libqdutils/display_config.cpp
In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
In file included from hardware/qcom/display/sdm845/libqdutils/display_config.h:35:
vendor/qcom/opensource/commonsys-intf/display/gralloc/gralloc_priv.h:29:9: warning: Warning: gralloc_priv.h is deprecated [-W#pragma-messages]
#pragma message "Warning: gralloc_priv.h is deprecated"
        ^
In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
In file included from hardware/qcom/display/sdm845/libqdutils/display_config.h:36:
In file included from vendor/qcom/opensource/commonsys-intf/display/libqdmetadata/qdMetaData.h:41:
vendor/qcom/opensource/commonsys-intf/display/gralloc/QtiGrallocPriv.h:43:9: warning: QtiGrallocPriv.h should not be included [-W#pragma-messages]
#pragma message "QtiGrallocPriv.h should not be included"
        ^
In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
In file included from hardware/qcom/display/sdm845/libqdutils/display_config.h:36:
vendor/qcom/opensource/commonsys-intf/display/libqdmetadata/qdMetaData.h:45:9: warning: qdMetaData.h is being deprecated [-W#pragma-messages]
#pragma message "qdMetaData.h is being deprecated"
        ^
In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
hardware/qcom/display/sdm845/libqdutils/display_config.h:120:28: error: unknown type name 'HSICData_t'
int setHSIC(int dpy, const HSICData_t& hsic_data);
                           ^
hardware/qcom/display/sdm845/libqdutils/display_config.cpp:88:28: error: unknown type name 'HSICData_t'
int setHSIC(int dpy, const HSICData_t& hsic_data) {
                           ^
3 warnings and 2 errors generated.
```
I think this is because the Android 11 caf code of sdm845 is still not launched. 
And the type HSICData_t no longer exists in vendor_qcom-opensource_display-commonsys-intf. 

I think you can following the example of lineage-18.0-caf-sdm845. 
Or you can try to repo sync the source code of the display from LA.UM.9.8.r1-03000-SDM710.0, but I am not sure that it will work on sdm845 phones。
https://github.com/LineageOS/android_hardware_qcom_display/tree/lineage-18.0-caf-sdm845

**Comment by Klozz** [comment]
> Sorry i'm here again for help.
> 
> ```
> [ 51% 82170/159540] //hardware/qcom/display/sdm845/libqdutils:libqdutils clang++ display_config.cpp
> FAILED: /home/navlys/XPe/out/soong/.intermediates/hardware/qcom/display/sdm845/libqdutils/libqdutils/android_vendor.30_arm64_armv8-2a_shared/obj/hardware/qcom/display/sdm845/libqdutils/display_config.o
> PWD=/proc/self/cwd /usr/bin/ccache vendor/qcom/sdclang/bin/clang++ -c -Wno-enum-compare -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -Wno-null-dereference -Wno-pointer-compare -Wno-xor-used-as-pow -Wno-final-dtor-non-final-class -D__ANDROID_VNDK__  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wno-c99-designator -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -march=armv8.2a  -target aarch64-linux-android30 -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -fPIC -Wsign-promo -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -Ihardware/qcom/display/sdm845/libqdutils -Ihardware/qcom/display/sdm845/include -Ihardware/qcom/display/sdm845/libcopybit -Ihardware/qcom/display/sdm845/libdrmutils -Ihardware/qcom/display/sdm845/libqdutils -Ihardware/qcom/display/sdm845/libqservice -Ihardware/qcom/display/sdm845/gpu_tonemapper -Ihardware/qcom/display/sdm845/sdm/include -Ihardware/qcom/display/sdm845/gralloc -Ihardware/qcom/display/sdm845/libdebug -Ihardware/libhardware/include -Isystem/media/audio/include -Isystem/core/libcutils/include_vndk -Isystem/core/libsystem/include -Isystem/bt/types -Ivendor/qcom/opensource/commonsys-intf/display/gralloc -Ivendor/qcom/opensource/commonsys-intf/display/include -Ivendor/qcom/opensource/commonsys-intf/display/libqdmetadata -Ivendor/qcom/opensource/commonsys-intf/display/services -Isystem/core/libutils/include -Isystem/core/libbacktrace/include -Isystem/core/liblog/include_vndk -Isystem/core/libprocessgroup/include -Iexternal/libcxxabi/include -Isystem/core/libcutils/include -Iframeworks/native/libs/binder/include -Isystem/core/base/include -I/home/navlys/XPe/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-2a_shared/gen/aidl -Iexternal/libcxx/include -isystem /home/navlys/XPe/out/soong/.intermediates/bionic/libc/libc.llndk/android_vendor.30_arm64_armv8-2a_shared/gen/include -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -Wno-missing-field-initializers -Wconversion -Wall -Werror '-DLOG_TAG="qdutils"' -Wno-sign-conversion -DDO_NOT_CHECK_MANUAL_BINDER_INTERFACES -std=gnu++17 -fno-rtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-string-compare -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-pessimizing-move  -Wno-alloca -Wno-bool-operation -Wno-c++17-extensions -Wno-c99-designator -Wno-dangling-gsl -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-copy -Wno-deprecated-enum-enum-conversion -Wno-final-dtor-non-final-class -Wno-implicit-fallthrough -Wno-implicit-int-float-conversion -Wno-incomplete-setjmp-declaration -Wno-int-in-bool-context -Wno-invalid-partial-specialization -Wno-misleading-indentation -Wno-pointer-compare -Wno-range-loop-analysis -Wno-reorder-init-list -Wno-sizeof-array-div-Wno-xor-used-as-pow -Wno-string-compare -Wno-tautological-overlap-compare -Wno-thread-safety-analysis -Wno-unknown-warning-option -Wno-unsequenced -Wno-unused-comparison -Wno-wrong-info -Wno-zero-as-null-pointer-constant -flax-vector-conversions=all -fsplit-lto-unit -MD -MF /home/navlys/XPe/out/soong/.intermediates/hardware/qcom/display/sdm845/libqdutils/libqdutils/android_vendor.30_arm64_armv8-2a_shared/obj/hardware/qcom/display/sdm845/libqdutils/display_config.o.d -o /home/navlys/XPe/out/soong/.intermediates/hardware/qcom/display/sdm845/libqdutils/libqdutils/android_vendor.30_arm64_armv8-2a_shared/obj/hardware/qcom/display/sdm845/libqdutils/display_config.o hardware/qcom/display/sdm845/libqdutils/display_config.cpp
> In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
> In file included from hardware/qcom/display/sdm845/libqdutils/display_config.h:35:
> vendor/qcom/opensource/commonsys-intf/display/gralloc/gralloc_priv.h:29:9: warning: Warning: gralloc_priv.h is deprecated [-W#pragma-messages]
> #pragma message "Warning: gralloc_priv.h is deprecated"
>         ^
> In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
> In file included from hardware/qcom/display/sdm845/libqdutils/display_config.h:36:
> In file included from vendor/qcom/opensource/commonsys-intf/display/libqdmetadata/qdMetaData.h:41:
> vendor/qcom/opensource/commonsys-intf/display/gralloc/QtiGrallocPriv.h:43:9: warning: QtiGrallocPriv.h should not be included [-W#pragma-messages]
> #pragma message "QtiGrallocPriv.h should not be included"
>         ^
> In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
> In file included from hardware/qcom/display/sdm845/libqdutils/display_config.h:36:
> vendor/qcom/opensource/commonsys-intf/display/libqdmetadata/qdMetaData.h:45:9: warning: qdMetaData.h is being deprecated [-W#pragma-messages]
> #pragma message "qdMetaData.h is being deprecated"
>         ^
> In file included from hardware/qcom/display/sdm845/libqdutils/display_config.cpp:35:
> hardware/qcom/display/sdm845/libqdutils/display_config.h:120:28: error: unknown type name 'HSICData_t'
> int setHSIC(int dpy, const HSICData_t& hsic_data);
>                            ^
> hardware/qcom/display/sdm845/libqdutils/display_config.cpp:88:28: error: unknown type name 'HSICData_t'
> int setHSIC(int dpy, const HSICData_t& hsic_data) {
>                            ^
> 3 warnings and 2 errors generated.
> ```
> 
> I think this is because the Android 11 caf code of sdm845 is still not launched.
> And the type HSICData_t no longer exists in vendor_qcom-opensource_display-commonsys-intf.
> 
> I think you can following the example of lineage-18.0-caf-sdm845.
> Or you can try to repo sync the source code of the display from LA.UM.9.8.r1-03000-SDM710.0, but I am not sure that it will work on sdm845 phones。
> https://github.com/LineageOS/android_hardware_qcom_display/tree/lineage-18.0-caf-sdm845

display hal is from LA.UM9 with LOS commits.

**Comment by Klozz** [comment]
Hello you can fork lineage HALS only remove the folder called commonsys-intf
and fork 
https://github.com/TheXPerienceProject/vendor-qcom-opensource-display-commonsys-intf/tree/xpe-15.0-oldhals
under vendor/qcom/opensource/commonsys-intf/display
is from LA.UM.8XXX adapted to work on LA.UM9 Source (aka android R in CAF)
I close this issue if u have any other problem you can open other issue :) good day.
